export const loginUrl = "http://localhost:5000/imgToText/api/v1/login"
export const registerUrl = "http://localhost:5000/imgToText/api/v1/register" 
export const saveImageUrl = "http://localhost:5000/imgToText/api/v1/imgData"
export const returnImageDataUrl = "http://localhost:5000/imgToText/api/v1/imgDatas"
export const getSingleImageDataIUrl = "http://localhost:5000/imgToText/api/v1/imgData/"