export const loginUrl = "https://backend-imgtotext.onrender.com/imgToText/api/v1/login"
export const registerUrl = "https://backend-imgtotext.onrender.com/imgToText/api/v1/register" 
export const saveImageUrl = "https://backend-imgtotext.onrender.com/imgToText/api/v1/imgData"
export const returnImageDataUrl = "https://backend-imgtotext.onrender.com/imgToText/api/v1/imgDatas"
export const getSingleImageDataIUrl = "https://backend-imgtotext.onrender.com/imgToText/api/v1/imgData/"